### ISSUE TITLE
Compilation error on Import Oracle

### ISSUE THREAD

**Issue by santhupolaris** [orisi/orisi#93]
Hi All,

i am trying to execute project from https://github.com/orisi/orisi and performed all steps as per the document in https://github.com/orisi/wiki/wiki/Installing-the-oracle-node

but i am getting this errors when i try to execute ./runoracle.sh

how can i resolve this errors i have checked Oracle Packages is installed and listing on executing this command "pydoc moudles"

 File "/home/vagrant/orisi/src/run_oracle.py", line 4, in <module>
    from oracle.oracle import Oracle
  File "/home/vagrant/orisi/src/oracle/oracle.py", line 8, in <module>
    from shared.fastproto import(
  File "/home/vagrant/orisi/src/shared/fastproto.py", line 2, in <module>
    import requests
ImportError: No module named requests

Thanks
Santhosh.

**Comment by kolinko** [comment]
Santhosh,
We stopped developing the project around a year ago, so even as you go over this, there will be a ton of obstacles before you can run the oracle. You also have to figure it by yourself. In this case I suggest googling "ImportError: No module named requests" - you'll get a ton of explanations for as why Python throws this.

**Comment by santhupolaris** [comment]
Hi Tomasz,

Thanks for your reply.
is there any alternative solution similar to Orisi with Oracle to create Smart contract on BlockChian  which is available as Opensource.

Thanks
Santhosh

-----Tomasz Kolinko notifications@github.com wrote: -----
To: orisi/orisi orisi@noreply.github.com

**Comment by kolinko** [comment]
As far as I know - nope. There was Codius, but it's defunct as well now.
